### ISSUE TITLE
Timestamp in Logical ID redeploys the Custom Resource unnecessarily

### ISSUE THREAD

**Issue by abhishandilya** [cdklabs/cdk-docker-image-deployment#518]
https://github.com/cdklabs/cdk-docker-image-deployment/blob/6e5538bf864d9a8f11f1ab596fc88d6d2f05bdc9/src/docker-image-deployment.ts#L114

**Comment by abhishandilya** [comment]
no one really looks at issues in this repo

**Comment by nw-kohei-ito** [comment]
Why is this feature not planned?
The cdk diff output is frustrating for me because of the custom resource changes. 
How does everyone else handle these frustrating diffs?

**Comment by abhishandilya** [comment]
I recommend forking this repo and change it yourself.
